### PR TITLE
Apply example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Apply example_ynh*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
@tituspijean , I think, I've solved the `CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file`
When it happens, just before there is:
`[ERR] The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/share/jellyfin/web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings.`

So jellyfin service start before jellyfin-web is installed ...

**Comment by yalh76** [comment]
Sometimes upgrade check fails because previous install fails ...

**Review by tituspijean — APPROVED** [review]
Let's ignore the failing upgrade then. Good catch with the install order of the web package!

**Pull request merged**
