### PR TITLE
V10.8.13

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by Thovi98** [comment]
> See the post about this release, there is a change about ffmpeg path : https://jellyfin.org/posts/jellyfin-security-and-you

It's written that:
> As part of this release, we have made a change to the behaviour of the "FFmpeg path" GUI configuration option in Jellyfin. Specifically, in version 10.8.13, this functionality has been disabled, and will be fully replaced in the next major version (10.9.0)

So as the functionality is disabled in 10.8.13 I don't think it has to be updated?

Thanks for the update @tituspijean!

**Comment by Salamandar** [comment]
Indeed. I was mostly thinking about the cmdline flag.

**Comment by Salamandar** [comment]
!testme

**Pull request merged**
