### PR TITLE
Testing

### LINKED ISSUE #54: Unable to install plugins on stock installation
I was unable to install any plugin until I manually created the folder and used `chown` to give permission to the `jellyfin` user group. Maybe, consider creating the plugins folder at `/var/lib/jellyfi` as path of the install script?

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to version 10.7.0 
- Update ldap.src

Closes  #54

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by Thovi98** [comment]
I’ve just tried a fresh install of Jellyfin testing and it looks like working great !
But I’ve configured myself as admin user, and it seems that I’m not, so I cannot configure my storage or so...

**Comment by ericgaspar** [comment]
I just tried and I have access to the administration interface with the specified admin. I do not have access to the admin interface with another account (as expected). Did you upgrade or fresh install the app?

**Comment by Thovi98** [comment]
I’ve just reinstalled it, and now works great, thanks !

**Review by tituspijean — APPROVED** [review]
🚀

**Pull request merged**
