### PR TITLE
Upgrade to 10.8.0

### PR DESCRIPTION
**Pull request by Salamandar**
## Problem

- Jellyfin will soon upgrade and I'm afraid this will break a lot of things

## Solution

- Testing a bit before the official release (and the official changelog unfortunately)

DONOTMERGE : This has changes on the .src.default files specific to pre-releases of Jellyfin.

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by tituspijean** [comment]
v10.8.0 has been released. 🙂

**Comment by tituspijean** [comment]
!gogogadgetotitus
!bullseyetestme

**Comment by tituspijean** [comment]
Upgrade successful on a RPi 4. 🚀

**Comment by Salamandar** [comment]
@tituspijean Nice ! No login issue after the upgrade ? The previous RCs had a weird issue.

**Comment by tituspijean** [comment]
It looks like it's OK. It added a default bind user, but it seemed to be working anyways.

**Comment by Salamandar** [comment]
I rebased the branch on `testing`.

**Pull request merged**
