### PR TITLE
Full fix

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- *Full fix*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Review by tituspijean — APPROVED** [review]
LGTM, I think?
I will keep myself out of this one, my brain is a bit toast.

(I do not understant where all these commits come from, have you forgotten a `rebase`?
And I do not see how it is a "full fix" of the recent upgrade and restore issues. But see no malice here, I merely end up being out of the loop of my own mess)

**Comment by yalh76** [comment]
> (I do not understand where all these commits come from, have you forgotten a `rebase`?

I don't know either... I didn't do a rebase. I don't use to do rebase...

> And I do not see how it is a "full fix" of the recent upgrade and restore issues. But see no malice here, I merely end up being out of the loop of my own mess)

I didn't knew how to name that PR, and as there was a lot of stuff... full fix seems OK ^^

**Comment by ericgaspar** [comment]
I really like `full fix` naming, very reassuring on this precarious time we are living in ...

**Pull request merged**
