### PR TITLE
Fix update package checker

### PR DESCRIPTION
**Pull request by Salamandar**
!testme

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by tituspijean** [comment]
@Salamandar what's the status of this? (I'm a bit confused by the 502 error)

**Comment by Salamandar** [comment]
!testme after a rebase :)

**Comment by tituspijean** [comment]
I think we lost the capability to test from older version with packaging v2. IIRC you had written a helper to fetch the older versions in the archives, right?

**Pull request closed without merging**
