### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Salamandar** [comment]
Upgrade did not go smoothly for me. almost-empty /var/lib/jellyfin…

**Review by Salamandar — CHANGES_REQUESTED** [review]
OK so "Upgrading packages..." completely deleted my /var/lib/jellyfin directory.

Actually i think it even removed the system user, recreated-it (at one moment ls -lah /var/lib/jellyfin did not show `jellyfin:jellyfin` but `991:991` as owners… then the content disappeared.

**Comment by Salamandar** [comment]
Ok bug found and fixed. I stupidly removed the packages to make things easier, but... i shouldn't have...

Hopefully jellyfin doesn't depend on jellyfin-ffmpeg*, so i can remove-and-install ffmpeg5 to ffmpeg6 separately from jellyfin itself.

Tested on my server, works flawlessly.

**Review by Salamandar — APPROVED** [review]

**Pull request merged**
