### PR TITLE
Fix the mess

### LINKED ISSUE #56: Impossible to restore backup or do a install on a new YunoHost system
Hi,

I'm trying to restore a jellyfin backup from January on YunoHost running on Raspberry 4 because of a corrupted SD Card.
So far I'm doing this without success.
I know that there were updates on jellyfin and YunoHost since January so I tried also a complete fresh installation.

This is what I did (several times):

- Flash my SD card with belenaEtcher and the latest release of YunoHost for Raspberry
- Running my Raspberry with this card
- Finalizing the post installation of YunoHost
- Create a user
- Install jellyfin (without success)

This is the complete Logfile of the jellyfin installation:
https://paste.yunohost.org/raw/orilicaluh

These are probably the important parts:
```
2021-03-10 06:19:09,868: DEBUG - The following packages will be REMOVED:
2021-03-10 06:19:09,869: DEBUG -   jellyfin-ynh-deps
2021-03-10 06:19:09,970: DEBUG - 0 upgraded, 0 newly installed, 1 to remove and 13 not upgraded.
2021-03-10 06:19:09,973: WARNING - E: Packages need to be removed but remove is disabled.
```

```
2021-03-10 06:19:11,282: DEBUG - + ynh_die '--message=Unable to install dependencies'
2021-03-10 06:19:11,283: WARNING - E: Unable to locate package (
2021-03-10 06:19:11,284: WARNING - E: Unable to locate package 10.6.4-1)
2021-03-10 06:19:11,286: WARNING - E: Couldn't find any package by glob '10.6.4-1)'
2021-03-10 06:19:11,287: WARNING - E: Couldn't find any package by regex '10.6.4-1)'
2021-03-10 06:19:11,390: DEBUG - + ret_code=1
2021-03-10 06:19:11,391: WARNING - Unable to install dependencies
2021-03-10 06:19:11,392: DEBUG - + echo 'Unable to install dependencies
```

Best regards, Stefan

### LINKED ISSUE #62: Restoration script fails
The upgrade failed (same as #60 I think), but I can't even restore the pre-upgrade backup. It fails here :
https://github.com/YunoHost-Apps/jellyfin_ynh/blob/63ab03ab79cc088a52b8a36fb4fdf5918bf0e14b/scripts/restore#L94
```

admin@salamandar ~ ??? sudo yunohost backup restore jellyfin-pre-upgrade1                                                                     ? 1 
Info: Preparing archive for restoration...
Info: Restoring jellyfin...
Info: [+...................] > Loading settings...
Info: [#++.................] > Validating restoration parameters...
Info: [###++...............] > Restoring the app main directory...
Info: [#####+..............] > Recreating the dedicated system user...
Info: [######+++++++.......] > Reinstalling dependencies...
Info: '/etc/apt/trusted.gpg.d/jellyfin.asc' wasn't deleted because it doesn't exist.
Info: [#############++.....] > Restoring the systemd configuration...
Error: Could not restore jellyfin
Info: The operation 'Restore 'jellyfin' from a backup archive' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20210312-141854-backup_restore_app-jellyfin --share' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - + not_mandatory=0
Info: DEBUG - + local archive_path=/home/yunohost.backup/tmp/jellyfin-pre-upgrade1/apps/jellyfin/backup/lib/systemd/system/jellyfin.service
Info: DEBUG - + '[' '!' -d /home/yunohost.backup/tmp/jellyfin-pre-upgrade1/apps/jellyfin/backup/lib/systemd/system/jellyfin.service ']'
Info: DEBUG - + '[' '!' -f /home/yunohost.backup/tmp/jellyfin-pre-upgrade1/apps/jellyfin/backup/lib/systemd/system/jellyfin.service ']'
Info: DEBUG - + '[' '!' -L /home/yunohost.backup/tmp/jellyfin-pre-upgrade1/apps/jellyfin/backup/lib/systemd/system/jellyfin.service ']'
Info: DEBUG - + '[' 0 == 0 ']'
Info: DEBUG - ++ _get_archive_path '"/lib/systemd/system/jellyfin.service"'
Info: DEBUG - ++ python -c '
Info: DEBUG - import sys
Info: DEBUG - import csv
Info: DEBUG - with open(sys.argv[1], '\''r'\'') as backup_file:
Info: DEBUG -     backup_csv = csv.DictReader(backup_file, fieldnames=['\''source'\'', '\''dest'\''])
Info: DEBUG -     for row in backup_csv:
Info: DEBUG -         if row['\''source'\'']==sys.argv[2].strip('\''"'\''):
Info: DEBUG -             print row['\''dest'\'']
Info: DEBUG -             sys.exit(0)
Info: DEBUG -     raise Exception('\''Original path for %s not found'\'' % sys.argv[2])
Info: DEBUG -     ' /home/yunohost.backup/tmp/jellyfin-pre-upgrade1/backup.csv '"/lib/systemd/system/jellyfin.service"'
Info: DEBUG - ++ return 1
Info: DEBUG - + archive_path=/home/yunohost.backup/tmp/jellyfin-pre-upgrade1/
Info: DEBUG - + ynh_exit_properly
Info: [....................] > Loading installation settings...
Info: [+...................] > Stopping and removing the systemd service...
Info: [#+..................] > Removing dependencies...
Info: [##+++++++++++.......] > Removing app main directory...
Info: '/etc/jellyfin' wasn't deleted because it doesn't exist.
Info: [#############+......] > Removing NGINX web server configuration...
Info: [##############++....] > Removing the dedicated system user...
Info: [####################] > Removal of jellyfin completed
```

The expected file is not in `/lib` but in `/usr/lib`.

### LINKED ISSUE #63: Upgrade does not upgrade (yeah, weird right ?)
The upgrade script only upgrades the debian package `jellyfin`, not `jellyfin-server` and `jellyfin-web`.

Here, I have jellyfin=10.7.0 installed, but 10.6.4 for the two others.

### LINKED ISSUE #68: Jellyfin no longer installable on latest YNH
### Describe the bug

When attempting to install jellyfin during the YNH install script, it attempts to install 3 packages `jellyfin`, `(=`, `1.7.0)` instead of installing `jellyfin (= 1.7.0)` this causes the installer to fail.

### Context

- Hardware: personal machine (quad-core x64 w/ 4gb ram)
- YunoHost version: 4.1.7.4
- I have access to my server: Direct Access
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.7.0~ynh2

### Steps to reproduce

`yunohost app install jellyfin --debug`

### Expected behavior

Jellyfin successfully installs

### Logs

https://paste.yunohost.org/raw/edupabemid

### LINKED ISSUE #70: Impossible to install: dependecies issue
### Describe the bug

Freshly installed x86 system. Other apps installed like discourse (unofficial).

### Context

- Hardware: x86 computer with RAID(hw)
- YunoHost version: 4.1.8
- I have access to my server through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No.
- trying to install package version/branch: 10.7.0

### Steps to reproduce

- Clicked on "Install with Yunohost",
- Failed to install dependencies
- tried via CLI,
- dump available here: https://paste.yunohost.org/raw/pinogihepa

### Expected behavior
Congraz, Jellyfin is installed!

### Extracts from the Logs (https://paste.yunohost.org/raw/pinogihepa)

32283 WARNING E: Packages need to be removed but remove is disabled.
32283 DEBUG   jellyfin-ynh-deps
32283 DEBUG 0 upgraded, 0 newly installed, 1 to remove and 25 not upgraded.
32284 DEBUG ++ cat /tmp/tmp.xXXeBfSnt2/dpkg_log
32284 DEBUG ++ grep -oP '(?<=-ynh-deps depends on ).*(?=; however)'
32284 DEBUG ++ tr '\n' ' '
32284 DEBUG + local 'problematic_dependencies=jellyfin (= 10.7.0-1) '
32284 DEBUG + [[ -n jellyfin (= 10.7.0-1)  ]]
32284 DEBUG + ynh_package_install jellyfin '(=' '10.7.0-1)' --dry-run
32284 DEBUG + ynh_apt --no-remove --option Dpkg::Options::=--force-confdef --option Dpkg::Options::=--force-confold install jellyfin '(=' '10.7.0-1)' --dry-run
32284 DEBUG + ynh_wait_dpkg_free
32284 DEBUG + local try
32284 DEBUG + set +o xtrace
32284 DEBUG + sed --quiet '/Reading state info/,$p'
32284 DEBUG + grep -v 'fix-broken\|Reading state info'
32385 DEBUG + return 0
32385 DEBUG + LC_ALL=C
32385 DEBUG + DEBIAN_FRONTEND=noninteractive
32385 DEBUG + apt-get --assume-yes --quiet -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --no-remove --option Dpkg::Options::=--force-confdef --option Dpkg::Options::=--force-confold install jellyfin '(=' '10.7.0-1)' --dry-run
32686 DEBUG + ynh_die '--message=Unable to install dependencies'
32686 WARNING E: Unable to locate package (
32687 DEBUG + local legacy_args=mc
32687 WARNING E: Unable to locate package 10.7.0-1)
32687 DEBUG + args_array=([m]=message= [c]=ret_code=)
32688 WARNING E: Couldn't find any package by glob '10.7.0-1)'
32688 DEBUG + local -A args_array
32688 WARNING E: Couldn't find any package by regex '10.7.0-1)'
32688 DEBUG + local message
32688 WARNING Unable to install dependencies

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem
- Upgrade to 10.7 was a mess for some users
- Restoration is not possible anymore due to removal of 10.6.4

## Solution
- I have no idea what I am doing
- Move away from the debian repo, from which older versions get deleted, preventing restoration if needed.
- Use deb files to install Jellyfin with variable source links 

Closes #56 
Closes #62
Closes #63 
Closes #68 
Closes #70

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
TODO:
- [ ] do not use automatic checksum retrieval (security issue)
- [ ] lower logging verbosity

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Ooookay so I extracted the log of the last timing out CI test: https://paste.yunohost.org/raw/iluhiwaxix
It hangs because `apt-get` asks what to do about `/etc/jellyfin/logging.json` being "manually" modified.

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/7)

**Comment by tituspijean** [comment]
OK. This was hell. Let's never do that again.

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/14)

**Review by yalh76 — APPROVED** [review]

**Pull request merged**
