### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
I don't know if that PR could help

# Own CI result for Revision: ece09f1a14403d0ad0bb259450c0674a774fe6c1 

image

**Review by ericgaspar — APPROVED** [review]
Great work!

**Comment by yalh76** [comment]
!testme

**Review by tituspijean — APPROVED** [review]

**Pull request merged**
