### PR TITLE
Update to latest jellyfin

### PR DESCRIPTION
**Pull request by studio315b**
## Problem
- YNH could not find jellyfin version 10.7.0-1 and caused it to be uninstallable (see #68)

## Solution
- Checking all available versions of the jellyfin package revealed that only 10.7.1-1 was available, so version was bumped

## PR Status
- [x] Code finished.
- [] Tested with Package_check.
- [x] Fix or enhancement tested.
- [?] Upgrade from last version tested. - Impossible, previous version didn't work at all
- [x] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by studio315b** [comment]
By the power of systemd, I invoke The Great App CI to test this Pull Request!

**Comment by studio315b** [comment]
!testme

**Comment by tituspijean** [comment]
Hello, and thank you for your contribution!

Only maintainers of repos can invoke the great CI. 😇 I am fixing underlying issues in #64, but I will with no problem merge your commits over there when I am done.

Meanwhile, you can prepare the package further more by bumping the version number in `manifest.json` and the `README`. ;)

**Review by guneydoganer — APPROVED** [review]
I think this can be resolved?

**Comment by tituspijean** [comment]
> I am fixing underlying issues in #64, but I will with no problem merge your commits over there when I am done.

Not yet.

**Comment by tituspijean** [comment]
v10.7.2 included in #64. 😉

**Pull request closed without merging**
