### PR TITLE
Adding LDAP plugin and permissions, upgrade to v1.7.0

### LINKED ISSUE #56: Impossible to restore backup or do a install on a new YunoHost system
Hi,

I'm trying to restore a jellyfin backup from January on YunoHost running on Raspberry 4 because of a corrupted SD Card.
So far I'm doing this without success.
I know that there were updates on jellyfin and YunoHost since January so I tried also a complete fresh installation.

This is what I did (several times):

- Flash my SD card with belenaEtcher and the latest release of YunoHost for Raspberry
- Running my Raspberry with this card
- Finalizing the post installation of YunoHost
- Create a user
- Install jellyfin (without success)

This is the complete Logfile of the jellyfin installation:
https://paste.yunohost.org/raw/orilicaluh

These are probably the important parts:
```
2021-03-10 06:19:09,868: DEBUG - The following packages will be REMOVED:
2021-03-10 06:19:09,869: DEBUG -   jellyfin-ynh-deps
2021-03-10 06:19:09,970: DEBUG - 0 upgraded, 0 newly installed, 1 to remove and 13 not upgraded.
2021-03-10 06:19:09,973: WARNING - E: Packages need to be removed but remove is disabled.
```

```
2021-03-10 06:19:11,282: DEBUG - + ynh_die '--message=Unable to install dependencies'
2021-03-10 06:19:11,283: WARNING - E: Unable to locate package (
2021-03-10 06:19:11,284: WARNING - E: Unable to locate package 10.6.4-1)
2021-03-10 06:19:11,286: WARNING - E: Couldn't find any package by glob '10.6.4-1)'
2021-03-10 06:19:11,287: WARNING - E: Couldn't find any package by regex '10.6.4-1)'
2021-03-10 06:19:11,390: DEBUG - + ret_code=1
2021-03-10 06:19:11,391: WARNING - Unable to install dependencies
2021-03-10 06:19:11,392: DEBUG - + echo 'Unable to install dependencies
```

Best regards, Stefan

### PR DESCRIPTION
**Pull request by tituspijean**
These modifications add:
- the permissions `jellyfin.main` and `jellyfin.admin`
- the LDAP plugin
- its configuration with YunoHost's LDAP settings

Includes upgrade to 1.7.0.

Closes #56

### CODE REVIEW

**Comment by tituspijean** [comment]
Right now I get these errors:

```
[2020-11-11 20:12:36.099 +01:00] [ERR] Failed to Connect or Bind to server
System.AggregateException: One or more errors occurred. (Name or service not known)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Novell.Directory.Ldap.Connection.Connect(String host, Int32 port, Int32 semaphoreId)
   at Novell.Directory.Ldap.LdapConnection.Connect(String host, Int32 port)
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.LocateLdapUser(String username)
[2020-11-11 20:12:36.100 +01:00] [ERR] Error authenticating with provider "LDAP-Authentication"
MediaBrowser.Controller.Authentication.AuthenticationException: Failed to Connect or Bind to server
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.LocateLdapUser(String username)
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
```

**Comment by liberodark** [comment]
Because your LDAP configuration is bad.

**Comment by Luxoris** [comment]
Hi ! 
I think that the  problem is not comming from bad ldap config but from outdated ldap extension for jellyfin :
https://github.com/jellyfin/jellyfin-plugin-ldapauth
They are many pull request on it to do the update but y think that the project is not maintained anymore :
https://github.com/jellyfin/jellyfin-plugin-ldapauth/pulls.

**Comment by kay0u** [comment]
New version, which should fix the issue with ldap: https://github.com/jellyfin/jellyfin-plugin-ldapauth/releases/tag/v10

**Comment by h3ndrik** [comment]
> New version, which should fix the issue with ldap: https://github.com/jellyfin/jellyfin-plugin-ldapauth/releases/tag/v10

this depends on jellyfin version 10.7 (and we're currently on 10.6)

**Comment by h3ndrik** [comment]
Just as a reference: I got jellyfin 10.7.0-rc4 working with the mentioned LDAP-Auth 10.0.0.0

Here's my working /var/lib/jellyfin/plugins/configurations/LDAP-Auth.xml
I took most of it from this pull-request. No guarantee the search filters are correct. But i think this should be easily doable with the upcoming release.

```
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <LdapServer>127.0.0.1</LdapServer>
  <LdapBaseDn>ou=users,dc=yunohost,dc=org</LdapBaseDn>
  <LdapPort>389</LdapPort>
  <LdapSearchAttributes>uid, mail</LdapSearchAttributes>
  <LdapUsernameAttribute>uid</LdapUsernameAttribute>
  <LdapSearchFilter>(permission=cn=jellyfin.main,ou=permission,dc=yunohost,dc=org)</LdapSearchFilter>
  <LdapAdminFilter>(permission=cn=jellyfin.admin,ou=permission,dc=yunohost,dc=org)</LdapAdminFilter>
  <LdapBindUser></LdapBindUser>
  <LdapBindPassword></LdapBindPassword>
  <CreateUsersFromLdap>true</CreateUsersFromLdap>
  <UseSsl>false</UseSsl>
  <UseStartTls>false</UseStartTls>
  <SkipSslVerify>false</SkipSslVerify>
</PluginConfiguration>
```

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Should be working now!

!tesme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by tituspijean** [comment]
Thanks! Do not merge yet, it seems ARM packages are not found/released yet.

**Pull request merged**
